### ISSUE TITLE
missing releases of the action itself?

### ISSUE THREAD

**Issue by ee7** [iffy/install-nim#22]
In [the Marketplace](https://github.com/marketplace/actions/install-nim), the latest version of this Action is written as `v4.0.2`. I believe that's because [its latest release](https://github.com/iffy/install-nim/releases) is `v4.0.2`.

However, [its latest tag](https://github.com/iffy/install-nim/tags) is `v.4.1.2`. So maybe some people using this action cannot use Nim 1.6.2 and 1.6.4 currently: https://github.com/iffy/install-nim/compare/v4.0.2...v4.1.2

I think e.g. `uses: iffy/install-nim@v4` would still use `v4.1.2`, but I haven't checked. And it may or may not prevent dependabot from creating a PR to bump e.g. `uses: iffy/install-nim@v4.0.2`.

**Comment by iffy** [comment]
Thanks for noticing this! It should be updated to 4.1.3 now.
