### ISSUE TITLE
missing releases of  v4.3.0, v4.3.1, and v4.4.0

### ISSUE THREAD

**Issue by ee7** [iffy/install-nim#29]
In [the Marketplace](https://github.com/marketplace/actions/install-nim), the Action's latest version is `v4.2.0`, which corresponds to the [latest release](https://github.com/iffy/install-nim/releases).

However, [the latest tag](https://github.com/iffy/install-nim/tags) is `v4.3.1`, and from https://github.com/iffy/install-nim/commit/531d17139d73db5c731e9937b48769d905c6a40f it seems like the intention was to tag `v4.4.0` too?

Is it intended that users shouldn't get the goodness of https://github.com/iffy/install-nim/compare/v4.2.0...531d17139d73db5c731e9937b48769d905c6a40f yet?

Previously: https://github.com/iffy/install-nim/issues/22

**Comment by iffy** [comment]
I'll be honest: I don't understand how the marketplace works :) I guess I have to make a GitHub Release every time to get it out there?

I've finally create a `v4` branch so you don't have to change the version in your workflows every time. Maybe I can get the Marketplace to display that.

**Comment by iffy** [comment]
> If you wanted to automate it

I think I eventually will :) Thanks for pinging me about this.

> there's still no release for v4.3.0 and v4.3.1

Does that mean you can't use those versions? Or does it just mean they don't show up in the marketplace?
