### ISSUE TITLE
Missing tag for supporting Nim 2.0.2 binary

### ISSUE THREAD

**Issue by ee7** [iffy/install-nim#45]
Hey @iffy. Can we have a new tag? :)

The [most recent tag](https://github.com/iffy/install-nim/tags) on GitHub is v5.0.2, so people using the latest tag [can't use](https://github.com/iffy/install-nim/compare/v5.0.2...3653c9d9e258ccd4c1f32c9faa892cc51ac973de) the Nim 2.0.2 or 1.6.18 binary, right?

**Comment by iffy** [comment]
Good catch! Here comes v5.0.3
